---
# defaults file for users
provisioned_users:

– name: user-one
  encrypted_password: $1$@YMgS-5Y$2lH.vkVmawJ810djjkGp70
  public_keys:
  – /home/$USER/.ssh/id_rsa.pub
  sudo: true
  adm: true

– name: user-two
encrypted_password: $1$@YMgS-5Y$2lH.vkVmawJ810djjkGp70
public_keys:
– /home/$USER/.ssh/id_rsa.pub
– /home/$USER/.ssh/id_rsa.pub
sudo: true
adm: true
– name: user-three
encrypted_password: $1$@YMgS-5Y$2lH.vkVmawJ810djjkGp70
public_keys:
– /home/$USER/.ssh/id_rsa.pub
– /home/$USER/.ssh/id_rsa.pub
– /home/$USER/.ssh/id_rsa.pub
sudo: false
adm: false
– name: user-four
encrypted_password: $1$@YMgS-5Y$2lH.vkVmawJ810djjkGp70
public_keys:
– /home/$USER/.ssh/id_rsa.pub
– /home/$USER/.ssh/id_rsa.pub
– /home/$USER/.ssh/id_rsa.pub
– /home/$USER/.ssh/id_rsa.pub
sudo: false
adm: false
