---
# tasks file for base
- name: install packages
  apt:
     pkg: "{{ item }}"
     state: present
  with_items:
     - fail2ban
     - git
     - htop
     - tmux
     - vim
     - unattended-upgrades
     - cowsay

- name: set the message of the day
  copy: 
     src: motd
     dest: /etc/motd
     mode: 664

- name: disable ssh root logins without the use of a valid ssh key
  lineinfile:
     dest: /etc/ssh/sshd_config
     state: present
     regexp: '^PermitRootLogin '
     line: ' PermitRootLogin without-password '
  notify: restart sshd

- name: disable ssh password logins for regular users
  lineinfile:
     dest: /etc/ssh/sshd_config
     state: present
     regexp: '^PasswordAuthentication '
     line: 'Password Authentication no'
  notify: restart sshd

- name: enable unattended security updates option
  debconf:
     name: unattended_upgrades
     question: 'unattended-upgrades/enable_auto_upgrades'
     value: 'true'
     vtype: 'boolean'
  notify: reconfigure unattended-upgrades
      
     

